
project_id = "mvaxosvtebdptnpykmbh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.get-quiz-results]
verify_jwt = true

[functions.save-quiz-result] 
verify_jwt = true

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = true
port = 54327

[vector]
enabled = false
