// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvaxosvtebdptnpykmbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12YXhvc3Z0ZWJkcHRucHlrbWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODAyOTIsImV4cCI6MjA1OTg1NjI5Mn0.ADA4Q7OGCPGCdkJ9kTfXlBrZx0RiSGkEhA_ppf9U_qI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);